//
//  Arrobj.h
//
//  Created on <%= Time.now.strftime("%Y-%m-%d") %>
//  Copyright (c) <%= Time.now.strftime("%Y") %>. All rights reserved.
//  Generated by Kilza https://github.com/Jaspion/Kilza
//

#import <Foundation/Foundation.h>


@interface Arrobj : NSObject <NSCoding, NSCopying>

@property (nonatomic, strong, nullable) NSString * str;
@property (nonatomic, strong, nullable) NSNumber * num;
@property (nonatomic, strong, nullable) NSNumber * flo;
@property (nonatomic, strong, nullable) NSNumber * boo;
@property (nonatomic, strong, nullable) id null;

+ (Arrobj * _Nonnull)modelWithDictionary:(NSDictionary * _Nonnull)dict;
+ (Arrobj * _Nonnull)modelWithString:(NSString * _Nonnull)json;

- (instancetype _Nonnull)initWithString:(NSString * _Nonnull)json;
- (instancetype _Nonnull)initWithDictionary:(NSDictionary * _Nonnull)dict;
- (NSDictionary * _Nonnull)dictionaryRepresentation;

@end
