//
//  Obj.swift
//
//  Created on <%= Time.now.strftime("%Y-%m-%d") %>
//  Copyright (c) <%= Time.now.strftime("%Y") %>. All rights reserved.
//  Generated by Kilza https://github.com/Jaspion/Kilza
//

import Foundation

public class Obj: NSObject, NSCoding {
    // Original names
    static let kObjStr: String = "str"
    static let kObjNum: String = "num"
    static let kObjFlo: String = "flo"
    static let kObjBoo: String = "boo"

    public var str: String?
    public var num: Int?
    public var flo: Double?
    public var boo: Bool?

    public class func model(obj: AnyObject) -> Obj? {
        var instance: Obj?
        if (obj is String) {
            instance = Obj.init(str: obj as! String)
        } else if (obj is Dictionary<String, AnyObject>) {
            instance = Obj.init(dict: obj as! Dictionary)
        }
        return instance
    }

    public convenience init?(str: String) {
        if let data = str.dataUsingEncoding(NSUTF8StringEncoding) {
            do {
                let object: AnyObject = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.AllowFragments)
                self.init(dict: object as! Dictionary)
            } catch _ as NSError {
                self.init(dict: Dictionary())
            }
        } else {
            self.init(dict: Dictionary())
        }
    }

    public init?(dict: Dictionary<String, AnyObject>) {
        super.init()
        self.str = objectOrNil(forKey: Obj.kObjStr, fromDictionary:dict) as? String
        self.num = objectOrNil(forKey: Obj.kObjNum, fromDictionary:dict) as? Int
        self.flo = objectOrNil(forKey: Obj.kObjFlo, fromDictionary:dict) as? Double
        self.boo = objectOrNil(forKey: Obj.kObjBoo, fromDictionary:dict) as? Bool
    }

    public func dictionaryRepresentation() -> Dictionary<String, AnyObject> {
        var mutableDict: Dictionary = [String: AnyObject]()
        mutableDict[Obj.kObjStr] = self.str
        mutableDict[Obj.kObjNum] = self.num
        mutableDict[Obj.kObjFlo] = self.flo
        mutableDict[Obj.kObjBoo] = self.boo
        return NSDictionary.init(dictionary: mutableDict) as! Dictionary<String, AnyObject>
    }

    public func objectOrNil(forKey key: String, fromDictionary dict: Dictionary<String, AnyObject>) -> AnyObject?
    {
        if let object: AnyObject = dict[key] {
            if !(object is NSNull) {
                return object
            }
        }
        return nil
    }

    required public init(coder aDecoder: NSCoder) {
        self.str = aDecoder.decodeObjectForKey(Obj.kObjStr)! as? String
        self.num = aDecoder.decodeObjectForKey(Obj.kObjNum)! as? Int
        self.flo = aDecoder.decodeObjectForKey(Obj.kObjFlo)! as? Double
        self.boo = aDecoder.decodeObjectForKey(Obj.kObjBoo)! as? Bool
    }

    public func encodeWithCoder(aCoder: NSCoder) {
        aCoder.encodeObject(str, forKey:Obj.kObjStr)
        aCoder.encodeObject(num, forKey:Obj.kObjNum)
        aCoder.encodeObject(flo, forKey:Obj.kObjFlo)
        aCoder.encodeObject(boo, forKey:Obj.kObjBoo)
    }

    override public var description: String {
        get {
            return "\(dictionaryRepresentation())"
        }
    }
}
