/**
* Created on <%= Time.now.strftime("%Y-%m-%d") %>
* Generated by Kilza https://github.com/Jaspion/Kilza
*/
package ;

import android.os.Parcelable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;

import java.io.Serializable;

import org.json.*;

public class Arrobj implements Parcelable, Serializable
{
    private static final String FIELD_STR = "str";
    private static final String FIELD_NUM = "num";
    private static final String FIELD_FLO = "flo";
    private static final String FIELD_BOO = "boo";
    private static final String FIELD__NULL = "null";

    @Expose
    @SerializedName(FIELD_STR)
    private String str;

    @Expose
    @SerializedName(FIELD_NUM)
    private Long num;

    @Expose
    @SerializedName(FIELD_FLO)
    private Double flo;

    @Expose
    @SerializedName(FIELD_BOO)
    private Boolean boo;

    @Expose
    @SerializedName(FIELD__NULL)
    private Object _null;

    public Arrobj() {

    }

    public Arrobj(JSONObject jsonObject) {
        parseObject(jsonObject);
    }

    public Arrobj(String jsonString) {
        try {
            parseString(jsonString);
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    protected void parseString(String jsonString) throws JSONException {
        JSONObject jsonObject = new JSONObject(jsonString);
        parseObject(jsonObject);
    }

    protected void parseObject(JSONObject object)
    {
        this.str = object.optString(FIELD_STR);
        this.num = object.optLong(FIELD_NUM);
        this.flo = object.optDouble(FIELD_FLO);
        this.boo = object.optBoolean(FIELD_BOO);
        this._null = object.opt(FIELD__NULL);
    }

    public void setStr(String value) {
        this.str = value;
    }

    public String getStr() {
        return this.str;
    }

    public void setNum(Long value) {
        this.num = value;
    }

    public Long getNum() {
        return this.num;
    }

    public void setFlo(Double value) {
        this.flo = value;
    }

    public Double getFlo() {
        return this.flo;
    }

    public void setBoo(Boolean value) {
        this.boo = value;
    }

    public Boolean isBoo() {
        return this.boo;
    }

    public void setNull(Object value) {
        this._null = value;
    }

    public Object getNull() {
        return this._null;
    }


    @Override
    public String toString() {
        Gson gson = new GsonBuilder().excludeFieldsWithoutExposeAnnotation().create();
        return gson.toJson(this);
    }

    private Arrobj(Parcel in) {
        str = in.readString();
        num = in.readLong();
        flo = in.readDouble();
        boo = in.readByte() != 0;
        _null = in.readObject();
    }

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(Parcel out, int flags) {
        out.writeString(str);
        out.writeLong(num);
        out.writeDouble(flo);
        out.writeByte((byte) (boo ? 1 : 0));
        out.writeObject(_null);
    }

    public static final Parcelable.Creator<Arrobj> CREATOR = new Parcelable.Creator<Arrobj>() {
        public Arrobj createFromParcel(Parcel in) {
            return new Arrobj(in);
        }

        public Arrobj[] newArray(int size) {
            return new Arrobj[size];
        }
    };
}
