/**
* Created on <%= Time.now.strftime("%Y-%m-%d") %>
* Generated by Kilza https://github.com/Jaspion/Kilza
*/
package ;

import android.os.Parcelable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;

import java.io.Serializable;

import org.json.*;

public class NullClass implements Parcelable, Serializable
{

    public NullClass() {

    }

    public NullClass(JSONObject jsonObject) {
        parseObject(jsonObject);
    }

    public NullClass(String jsonString) {
        try {
            parseString(jsonString);
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    protected void parseString(String jsonString) throws JSONException {
        JSONObject jsonObject = new JSONObject(jsonString);
        parseObject(jsonObject);
    }

    protected void parseObject(JSONObject object)
    {
    }


    @Override
    public String toString() {
        Gson gson = new GsonBuilder().excludeFieldsWithoutExposeAnnotation().create();
        return gson.toJson(this);
    }

    private NullClass(Parcel in) {
    }

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(Parcel out, int flags) {
    }

    public static final Parcelable.Creator<NullClass> CREATOR = new Parcelable.Creator<NullClass>() {
        public NullClass createFromParcel(Parcel in) {
            return new NullClass(in);
        }

        public NullClass[] newArray(int size) {
            return new NullClass[size];
        }
    };
}
