/**
* Created on <%= Time.now.strftime("%Y-%m-%d") %>
* Generated by Kilza https://github.com/Jaspion/Kilza
*/
package ;

import android.os.Parcelable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;

import java.io.Serializable;

import org.json.*;

public class Space implements Parcelable, Serializable
{
    private static final String FIELD__1ONE = "1one";

    @Expose
    @SerializedName(FIELD__1ONE)
    private String _1one;

    public Space() {

    }

    public Space(JSONObject jsonObject) {
        parseObject(jsonObject);
    }

    public Space(String jsonString) {
        try {
            parseString(jsonString);
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    protected void parseString(String jsonString) throws JSONException {
        if (!jsonString.trim().startsWith("{"))
            jsonString = "{\"" + FIELD__1ONE + "\" : " + jsonString + "}";
        JSONObject jsonObject = new JSONObject(jsonString);
        parseObject(jsonObject);
    }

    protected void parseObject(JSONObject object)
    {
        this._1one = object.optString(FIELD__1ONE);
    }

    public void set1one(String value) {
        this._1one = value;
    }

    public String get1one() {
        return this._1one;
    }


    @Override
    public String toString() {
        Gson gson = new GsonBuilder().excludeFieldsWithoutExposeAnnotation().create();
        return gson.toJson(this);
    }

    private Space(Parcel in) {
        _1one = in.readString();
    }

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(Parcel out, int flags) {
        out.writeString(_1one);
    }

    public static final Parcelable.Creator<Space> CREATOR = new Parcelable.Creator<Space>() {
        public Space createFromParcel(Parcel in) {
            return new Space(in);
        }

        public Space[] newArray(int size) {
            return new Space[size];
        }
    };
}
