//
//  ReservedWords.h
//
//  Created on <%= Time.now.strftime("%Y-%m-%d") %>
//  Copyright (c) <%= Time.now.strftime("%Y") %>. All rights reserved.
//  Generated by Kilza https://github.com/Jaspion/Kilza
//

#import <Foundation/Foundation.h>

@class ReturnClass;

@interface ReservedWords : NSObject <NSCoding, NSCopying>

@property (nonatomic, strong) NSString * _if;
@property (nonatomic, strong) ReturnClass * _return;

+ (ReservedWords *)modelWithDictionary:(NSDictionary *)dict;
+ (ReservedWords *)modelWithString:(NSString *)json;

- (instancetype)initWithString:(NSString *)json;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end
