//
//  ReturnClass.h
//
//  Created on <%= Time.now.strftime("%Y-%m-%d") %>
//  Copyright (c) <%= Time.now.strftime("%Y") %>. All rights reserved.
//  Generated by Kilza https://github.com/Jaspion/Kilza
//

#import <Foundation/Foundation.h>


@interface ReturnClass : NSObject <NSCoding, NSCopying>

@property (nonatomic, strong) NSNumber * _id;

+ (ReturnClass *)modelWithDictionary:(NSDictionary *)dict;
+ (ReturnClass *)modelWithString:(NSString *)json;

- (instancetype)initWithString:(NSString *)json;
- (instancetype)initWithDictionary:(NSDictionary *)dict;
- (NSDictionary *)dictionaryRepresentation;

@end
